[package]
name = "chess_ai"
version = "1.0.1"
edition = "2018"

[lib]
name = "chess_ai"
crate-type = ["cdylib"]

[dependencies]
colored = "2.0.0"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
