#! /usr/bin/env python3

from argparse import ArgumentParser
from chessai_interface import GameWindow
from chessai_interface.benchmarker import BenchMarker


parser = ArgumentParser(
    "Chess ai",
    description="Chess ai CLI"
)

sub_parsers = parser.add_subparsers(
    title="COMMAND",
    dest="command",
    required=True
)

gui_parser = sub_parsers.add_parser("gui", description="Start GUI", help="Start the GUI")
bench_parser = sub_parsers.add_parser("benchmark", description="Run benchmarks", help="Run benchmarks")

gui_parser.add_argument(
    "--fen-code",
    dest="fen_code",
    default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
    help="The fen code to use at the start of the game"
)

gui_parser.add_argument(
    "--log-file-name",
    "-l",
    dest="log_file_name",
    type=str,
    default=None,
    help="The file to write the logs to"
)

gui_parser.add_argument(
    "--color",
    default="black",
    help="The color that the AI will play as"
)

bench_parser.add_argument(
    "benchmark_name",
    type=str,
    help="Name for the benchmark"
)

bench_parser.add_argument(
    "--runs",
    type=int,
    default=10,
    help="Amount of runs to do to get an average"
)

args = parser.parse_args()

if args.command == "gui":
    root = GameWindow(args.fen_code, args.log_file_name, args.color)
    root.mainloop()
elif args.command == "benchmark":
    bencher = BenchMarker(args.benchmark_name, args.runs)
    bencher.run()
